In [11]:
import pandas as pd
# Loading iris
df = pd.read_csv('./wisc_bc_ContinuousVar.csv')
# df.head()
# print(df.describe())
# #data preprocessing
# df['Species'] = pd.Categorical(df['Species'])  # convert Species column to categorical data type
df.head(10)
df = df.dropna() # drops NaN values 
print(df[df.isna().any(axis=1)]) # shows NaN values in data frame if it exists




df = df.dropna() # drops NaN values 
#print(df[df.isna().any(axis=1)]) # shows NaN values in data frame if it exists

# Splitting the dataset
attr = df.drop(columns = ['diagnosis', 'id'])  # features
labels = df['diagnosis']  # target variable
labels = labels.map({'M': 0, 'B': 1})


Empty DataFrame
Columns: [id, diagnosis, radius_mean, texture_mean, perimeter_mean, area_mean, smoothness_mean, compactness_mean, concavity_mean, concave points_mean, symmetry_mean, fractal_dimension_mean, radius_se, texture_se, perimeter_se, area_se, smoothness_se, compactness_se, concavity_se, concave points_se, symmetry_se, fractal_dimension_se, radius_worst, texture_worst, perimeter_worst, area_worst, smoothness_worst, compactness_worst, concavity_worst, concave points_worst, symmetry_worst, fractal_dimension_worst]
Index: []

[0 rows x 32 columns]


In [14]:
# Separate features and target
X = attr.values  # Assuming the last column is the target
y = labels.values

# Normalize features
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

# Split data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

i = X_train[0]

In [20]:
## define the initial weights, input and sigmoid function and caculate the forward feed
import numpy as np
from scipy.special import expit, logit

import numpy as np

# Initialize weight matrix with random values
num_hidden_neurons = 5
#num_features=len(attr.columns)
weight_ih = np.random.rand(len(attr.columns), num_hidden_neurons)


print( weight_ih)
print()
weight_ho = np.random.rand(num_hidden_neurons + 1)
print(weight_ho)
print()
i=X_train[0]
out_hiddenL=expit(i.dot(weight_ih)) 
print(out_hiddenL)
one=np.array([1])
input_outputL=np.concatenate((one,out_hiddenL),axis=0)
print(input_outputL)
out_outL=expit(input_outputL.dot(weight_ho)) 
print(out_outL)

[[0.04808839 0.59480291 0.66724803 0.77266286 0.00809628]
 [0.69024161 0.25863928 0.26820654 0.8168325  0.64760648]
 [0.4826889  0.7531197  0.21615819 0.62209187 0.93425995]
 [0.54200661 0.60450749 0.70544457 0.17198746 0.23005065]
 [0.973854   0.32102649 0.00952904 0.29007852 0.77683949]
 [0.33068711 0.64525123 0.97004208 0.76862741 0.32651535]
 [0.54221827 0.84934093 0.69154541 0.68947396 0.09866718]
 [0.51474194 0.96039545 0.63873137 0.06994908 0.22626543]
 [0.20844631 0.4888792  0.69401194 0.71057652 0.38941888]
 [0.50520999 0.46114096 0.50092072 0.70991044 0.1248878 ]
 [0.48984889 0.77598174 0.10708371 0.36666875 0.11249925]
 [0.04417046 0.92615114 0.06346649 0.36069674 0.58797975]
 [0.70055295 0.69195477 0.81629387 0.88832023 0.36259812]
 [0.60182139 0.01207736 0.98672742 0.56510184 0.95019736]
 [0.37928785 0.74906261 0.07272595 0.27591054 0.62511806]
 [0.35617423 0.55456956 0.62073311 0.15556891 0.1056406 ]
 [0.52005571 0.76431941 0.95901497 0.85647258 0.94209092]
 [0.65593285 0

In [21]:
Actual=.8
eta= .1
e=out_outL-Actual
print(e)
 

0.011991082149643173


In [22]:
delta= -1*(out_outL)*(1-out_outL)*e
print(delta)
DELTA=eta*delta*input_outputL
print(DELTA)
#-0.000820411
#-0.000647454
#-0.000670747

-0.0018305773629202662
[-0.00018306 -0.00016542 -0.00016393 -0.00016242 -0.00016473 -0.00015894]


In [23]:

New_ho=weight_ho + DELTA
print(New_ho)
print(weight_ho)
e_hidden=weight_ho[[1,2]].dot(delta)
print(e_hidden)
#-0.007383703
#-0.007383703


[0.82559167 0.21002046 0.16705144 0.19070819 0.0303041  0.11590752]
[0.82577473 0.21018588 0.16721537 0.19087061 0.03046883 0.11606646]
[-0.00038476 -0.0003061 ]


In [ ]:
# delta_h= e_hidden.dot(out_hiddenL.dot(1-out_hiddenL))
# print(delta_h)