In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


# import metrics to compute accuracy
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

from sklearn.svm import SVC

In [ ]:
  
# # IMPORT THE IRIS DATA FROM THE 
# # SKLEARN MODULE
# from sklearn.datasets import load_iris
  
# # LOAD THE IRIS DATASET BY CALLING
# # THE FUNCTION
# iris_data = load_iris()
 
  
# # PLACE THE IRIS DATA IN A PANDAS
# # DATAFRAME
# attr = pd.DataFrame(data=iris_data.data, 
#                   columns=iris_data.feature_names)
# target =pd.DataFrame({'Species': iris_data.target})

# # DISPLAY FIRST 5 RECORDS OF THE 
# # DATAFRAME
# target.head()
# attr.head(10)

In [2]:
# Loading iris
df = pd.read_csv('./breast-cancer-wisconsin.csv')
# df.head()
# print(df.describe())
# #data preprocessing
# df['Species'] = pd.Categorical(df['Species'])  # convert Species column to categorical data type
df.head(10)

Sample  F1  F2  F3  F4  F5  F6  F7  F8  F9  Class
0  1000025   5   1   1   1   2   1   3   1   1      2
1  1002945   5   4   4   5   7  10   3   2   1      2
2  1015425   3   1   1   1   2   2   3   1   1      2
3  1016277   6   8   8   1   3   4   3   7   1      2
4  1017023   4   1   1   3   2   1   3   1   1      2
5  1017122   8  10  10   8   7  10   9   7   1      4
6  1018099   1   1   1   1   2  10   3   1   1      2
7  1018561   2   1   2   1   2   1   3   1   1      2
8  1033078   2   1   1   1   2   1   1   1   5      2
9  1033078   4   2   1   1   2   1   2   1   1      2

In [8]:
df = df.dropna() # drops NaN values 
print(df[df.isna().any(axis=1)]) # shows NaN values in data frame if it exists


df['F6'] = pd.to_numeric(df['F6'], errors='coerce')

# Calculate the mean of 'F6', excluding NaN values
mean_f6 = df['F6'].mean()

# Replace NaN values in 'F6' with the calculated mean
df['F6'].fillna(mean_f6, inplace=True)

# Splitting the dataset
attr = df.drop(columns = ['Class', 'Sample']  # features
target = df['Class']  # target variable


attr.head()
# target.head()

SyntaxError: positional argument follows keyword argument (1688438560.py, line 14)

In [5]:
target.head()

0    2
1    2
2    2
3    2
4    2
Name: Class, dtype: int64

In [6]:
## using standard scaler instead of min max scaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit and transform the data
attr = pd.DataFrame(scaler.fit_transform(attr), columns=attr.columns)
attr.head()

ValueError: could not convert string to float: '?'

In [6]:

attr_train, attr_test, target_train,target_test  = train_test_split(attr, target,test_size = 0.25, random_state = 7, shuffle = True)
target_train.head()
# attr_train.head()
target_test.head()

149     Virginica
84     Versicolor
40         Setosa
66     Versicolor
106     Virginica
Name: Species, dtype: object

In [7]:
# import SVM classifier
from sklearn.svm import SVC

# import metrics to compute accuracy
from sklearn.metrics import accuracy_score


# instantiate classifier 
svc=SVC() 

# fit classifier to training set
svc.fit(attr_train,target_train)


# make predictions on test set
target_pred=svc.predict(attr_test)


# compute and print accuracy score
print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(target_test, target_pred)))
print()
print('Classification Report')
print(classification_report(target_test, target_pred))
print()
print('Confusion Matrix')
print(confusion_matrix(target_test, target_pred))



Model accuracy score with default hyperparameters: 1.0000

Classification Report
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        11
  Versicolor       1.00      1.00      1.00        14
   Virginica       1.00      1.00      1.00        13

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38


Confusion Matrix
[[11  0  0]
 [ 0 14  0]
 [ 0  0 13]]
